//Each new term in the Fibonacci sequence is generated by adding the previous two
// terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not
//exceed four million, find the sum of the even-valued terms.


var n1 = 1;
var n2 = 2;
var sum = 0;
var sumEven = 2;

var fibSeq = function (n){
	while(n2 < n){
		sum = n1 + n2;
		if (sum%2 === 0){
			sumEven += sum;
		}
		n1 = n2;
		n2 = sum;
	}
	return sumEven;
};
console.log (fibSeq(4000000))